language: node_js
node_js:
- '0.11'
- '0.10'
after_success:
- make coverage
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/tarmolov/bla.git
- git checkout master
- make build
- git add build
- git commit -m "Rebuild"
- git push origin master
env:
  global:
    secure: KyKfxDv/kWEU7ym9slCKgSaJc5Ujke8hdZrQsD3JVUZFRpQulCjVHJQx78IMl4EPULUr8NTmYbR9OXJWNAuDyJyoC8fEmWip9zcvVj2QJZ62T8VK2wy59tUieKqdhLz8Hug1oCZ/LjnYDsSjfXL+i+mRos686RH+RHbHk0FmZ7Q=
deploy:
  provider: npm
  email: tarmolov@gmail.com
  api_key:
    secure: LfLG35921234nZk3Me9Z3G3qy5NxJvZ5mLwJE3iTIloJlbDLgmaXlClYMVtO0JHD7/nLxZA1EE9lFJ1JexDNMCnH/eLqWDGui0YdAAAzysrNwlpoQNuRChxRL8lLaNAxilIDv/rQxCoKZCzT7apjU7nV1Of4SgJOYhOZ2kkmub0=
  on:
    tags: true
    all_branches: true
