language: node_js
node_js:
  - "0.11"
  - "0.10"
after_success: istanbul cover ./node_modules/mocha/bin/_mocha tests/lib tests/examples tests/api -- --recursive -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
