language: node_js
node_js:
- '0.10'
script: npm run travis
after_success:
  - make sauce
  - npm install coveralls@2.11.1 && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: tarmolov@gmail.com
  api_key:
    secure: LfLG35921234nZk3Me9Z3G3qy5NxJvZ5mLwJE3iTIloJlbDLgmaXlClYMVtO0JHD7/nLxZA1EE9lFJ1JexDNMCnH/eLqWDGui0YdAAAzysrNwlpoQNuRChxRL8lLaNAxilIDv/rQxCoKZCzT7apjU7nV1Of4SgJOYhOZ2kkmub0=
  on:
    tags: true
    all_branches: true
env:
  global:
  # SAUCE_USERNAME
  - secure: DX/yxjom3axs7bqbrjCRofDBfQEzmlCAW8pVLHTXdtX99PuxD5uZkkD9CJLGfssv9tgjdMRZmrr5YqM9ZCNO9poEqsA23fG7bm0dKrC8JklcXLkOGpuFTHcnBhF7hJCCFrba812X4viaXKUF4I4TuSeO6bkhp7Z/mv4KxD5lhT0=
  # SAUCE_ACCESS_KEY
  - secure: G2FidZTL4iENx5hvMaGAeKHkhiDQJFaJFodI9aOEOF/EsIEL8KUtwxoGv+K251GN4JbTwERCFD847Bs094c8ygQM2IpSMgvH/XiZ4GMqosJQJ0Hgb98o/mLMxjOLm9yW10dQBJA0iafLqjhnGJ2gkO1S6gKAcoPeqVse8eOh/3U=
