language: node_js
node_js:
- '0.10'
sudo: false
script: npm run travis
after_success:
- npm install coveralls@2.11.1 && cat ./coverage/lcov.info | coveralls
- zuul -- tools/zuul.js
deploy:
  provider: npm
  email: tarmolov@gmail.com
  api_key:
    secure: Ce8Pb8X1fCzLNxYNyJPe3fZTXQozU7tMNmwfRgWpRm0r/igo6DM+6DSj9uPTCdg1qy4kiRvxOjvm/zoOiJsY4+njhXuHpmCnn40cwrEoALyI+IAsNmPkKdTOcVQeylSiacglY6me7aZ5C3zYeLVpegHJnF59gv8EgsRRg2DBN2g=
  on:
    tags: true
    repo: baby-loris/bla
env:
  global:
  - secure: ClEcmw33CSP8L9gATIDPjZT/QS3EBrSx2XXAXNcl6K3AXODWqjMH4uzdQJnAYaYSlPkNWLZho+L4UyF9SQJiqdUfCkGE7wlw7765w6DVztMsuupPqiA4hrTGQgbnEsbFyayrsnSLg71/Kf6MV9fyEcJZ+HtXO29BvNpuTRuji0Y=
  - secure: O5gcZIv+clsJotxuNrCIJrFTffDfow6OnrGbhpNilurjnLLIKe7w4HFmjWVtRHmEH443LK5atC9UpBt4YAEoNEoXsAoYFbZIKi0gwZ74etJV70ttj/KrEZ7yUex7WY+mDmFqGt1wPSMkl6X3RkSVt8tOoxvCg3xhjd13AFKMHvw=
