language: node_js
node_js:
- '0.11'
- '0.10'
after_success:
- make coverage
deploy:
  provider: npm
  email: tarmolov@gmail.com
  api_key:
    secure: LfLG35921234nZk3Me9Z3G3qy5NxJvZ5mLwJE3iTIloJlbDLgmaXlClYMVtO0JHD7/nLxZA1EE9lFJ1JexDNMCnH/eLqWDGui0YdAAAzysrNwlpoQNuRChxRL8lLaNAxilIDv/rQxCoKZCzT7apjU7nV1Of4SgJOYhOZ2kkmub0=
  on:
    tags: true
    all_branches: true
