language: node_js
node_js:
- '0.11'
- '0.10'
after_success:
  - make coverage
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis"
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/tarmolov/baby-loris-api.git
  - git checkout master
  - make build
  - git add build
  - git commit -m "Rebuild"
  - git push origin master
env:
  global:
    secure: L7hbA0XDt6V7eXAJtSwG3OrPHsUE1M8/2pr0PCpvODRb7/J+Gqx5LRFa9ZSrnImwa79YBnDqIuT4ewTFYskMfGtvxSfXLK7z2tBXhgZvEXBwv1YryTvEMM4a5C7hGIrLeEgdNimUUqq42JwQYfvUhvHVO4IQk777ytCZsn2UIX0=
deploy:
  provider: npm
  email: tarmolov@gmail.com
  api_key:
    secure: LfLG35921234nZk3Me9Z3G3qy5NxJvZ5mLwJE3iTIloJlbDLgmaXlClYMVtO0JHD7/nLxZA1EE9lFJ1JexDNMCnH/eLqWDGui0YdAAAzysrNwlpoQNuRChxRL8lLaNAxilIDv/rQxCoKZCzT7apjU7nV1Of4SgJOYhOZ2kkmub0=
  on:
    tags: true
    all_branches: true
