ui: mocha-bdd
scripts:
  - "node_modules/chai/chai.js"
  - "node_modules/sinon/pkg/sinon.js"
  - "node_modules/ym/modules.js"
  - "node_modules/vow/lib/vow.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: latest
